# Generated by Django 5.0 on 2023-12-11 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astronomyshow',
            old_name='show_theme',
            new_name='show_themes',
        ),
    ]
