# Generated by Django 5.0 on 2023-12-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0003_rename_show_theme_astronomyshow_show_themes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='astronomyshow',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='showsession',
            options={'ordering': ['-show_time']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
        migrations.AlterField(
            model_name='showtheme',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='planetarium.reservation'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='show_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='planetarium.showsession'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('show_session', 'row', 'seat')},
        ),
    ]
