# Generated by Django 4.0.4 on 2023-12-11 14:04

from django.db import migrations, models
import planetarium.models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0004_alter_astronomyshow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='image',
            field=models.ImageField(null=True, upload_to=planetarium.models.astronomy_show_image_file_path),
        ),
    ]
